config/routes.rb
Unlocking::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users 
  resources :blackberries
  resources :alcatels
  resources :huwaeis
  resources :htcs
  resources :lgs
  resources :samsungs
  resources :iphones

  
  
  get "pages/contact"

end

app/models/huwaei.rb
class Huwaei < ActiveRecord::Base
  belongs_to :user
end

app/controllers/huwaeis_controller.rb
class HuwaeisController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_huwaei, only: [:show, :edit, :update, :destroy]

  # GET /huwaeis
  # GET /huwaeis.json
  def index
    @huwaeis = Huwaei.all
  end

  # GET /huwaeis/1
  # GET /huwaeis/1.json
  def show
  end

  # GET /huwaeis/new
  def new
    @huwaei = Huwaei.new
  end

  # GET /huwaeis/1/edit
  def edit
  end

  # POST /huwaeis
  # POST /huwaeis.json
  def create
    @huwaei = Huwaei.new(huwaei_params)

    respond_to do |format|
      if @huwaei.save
        format.html { redirect_to @huwaei, notice: 'Huwaei was successfully created.' }
        format.json { render action: 'show', status: :created, location: @huwaei }
      else
        format.html { render action: 'new' }
        format.json { render json: @huwaei.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /huwaeis/1
  # PATCH/PUT /huwaeis/1.json
  def update
    respond_to do |format|
      if @huwaei.update(huwaei_params)
        format.html { redirect_to @huwaei, notice: 'Huwaei was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @huwaei.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /huwaeis/1
  # DELETE /huwaeis/1.json
  def destroy
    @huwaei.destroy
    respond_to do |format|
      format.html { redirect_to huwaeis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_huwaei
      @huwaei = Huwaei.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def huwaei_params
      params.require(:huwaei).permit(:services, :imei, :response_email, :text_alert, :user_id)
    end
end

app/helpers/huwaeis_helper.rb
module HuwaeisHelper
end

app/views/huwaeis/_form.html.erb
<%= form_for @huwaei, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :services, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :services,['Huawei $8 (2-24hrs)'],:prompt => "Select One", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imei, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imei, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :response_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :response_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text_alert, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text_alert, :class => 'text_field' %>
    </div>
  </div>
 

  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                huwaeis_path, :class => 'btn' %>
  </div>
<% end %>

app/views/huwaeis/edit.html.erb
<%- model_class = Huwaei -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/huwaeis/index.html.erb
<%- model_class = Huwaei -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:services) %></th>
      <th><%= model_class.human_attribute_name(:imei) %></th>
      <th><%= model_class.human_attribute_name(:response_email) %></th>
      <th><%= model_class.human_attribute_name(:text_alert) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @huwaeis.each do |huwaei| %>
      <tr>
        <td><%= link_to huwaei.id, huwaei_path(huwaei) %></td>
        <td><%= huwaei.services %></td>
        <td><%= huwaei.imei %></td>
        <td><%= huwaei.response_email %></td>
        <td><%= huwaei.text_alert %></td>
        <td><%= huwaei.user_id %></td>
        <td><%=l huwaei.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_huwaei_path(huwaei), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      huwaei_path(huwaei),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_huwaei_path,
            :class => 'btn btn-primary' %>

app/views/huwaeis/new.html.erb
<%- model_class = Huwaei -%>
<div class="page-header">
  <h1>Huawei Service</h1>
</div>
<%= render :partial => 'form' %>

app/views/huwaeis/show.html.erb
<%- model_class = Huwaei -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:services) %>:</strong></dt>
  <dd><%= @huwaei.services %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imei) %>:</strong></dt>
  <dd><%= @huwaei.imei %></dd>
  <dt><strong><%= model_class.human_attribute_name(:response_email) %>:</strong></dt>
  <dd><%= @huwaei.response_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text_alert) %>:</strong></dt>
  <dd><%= @huwaei.text_alert %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @huwaei.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              huwaeis_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_huwaei_path(@huwaei), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              huwaei_path(@huwaei),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>