config/routes.rb
Unlocking::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users 
  resources :blackberries
  resources :alcatels
  resources :huwaeis
  resources :htcs
  resources :lgs
  resources :samsungs
  resources :iphones

  
  
  get "pages/contact"

end

app/models/lg.rb
class Lg < ActiveRecord::Base
  belongs_to :user
end

app/controllers/lgs_controller.rb
class LgsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_lg, only: [:show, :edit, :update, :destroy]

  # GET /lgs
  # GET /lgs.json
  def index
    @lgs = Lg.all
  end

  # GET /lgs/1
  # GET /lgs/1.json
  def show
  end

  # GET /lgs/new
  def new
    @lg = Lg.new
  end

  # GET /lgs/1/edit
  def edit
  end

  # POST /lgs
  # POST /lgs.json
  def create
    @lg = Lg.new(lg_params)

    respond_to do |format|
      if @lg.save
        format.html { redirect_to @lg, notice: 'Lg was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lg }
      else
        format.html { render action: 'new' }
        format.json { render json: @lg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgs/1
  # PATCH/PUT /lgs/1.json
  def update
    respond_to do |format|
      if @lg.update(lg_params)
        format.html { redirect_to @lg, notice: 'Lg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgs/1
  # DELETE /lgs/1.json
  def destroy
    @lg.destroy
    respond_to do |format|
      format.html { redirect_to lgs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lg
      @lg = Lg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lg_params
      params.require(:lg).permit(:services, :imei, :response_email, :text_alert, :user_id)
    end
end

app/helpers/lgs_helper.rb
module LgsHelper
end

app/views/lgs/_form.html.erb
<%= form_for @lg, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :services, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :services,['LG Wordwide $7 (10-15 minutes)'],:prompt=> "Select One", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imei, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imei, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :response_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :response_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text_alert, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text_alert, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lgs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lgs/edit.html.erb
<%- model_class = Lg -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lgs/index.html.erb
<%- model_class = Lg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:services) %></th>
      <th><%= model_class.human_attribute_name(:imei) %></th>
      <th><%= model_class.human_attribute_name(:response_email) %></th>
      <th><%= model_class.human_attribute_name(:text_alert) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lgs.each do |lg| %>
      <tr>
        <td><%= link_to lg.id, lg_path(lg) %></td>
        <td><%= lg.services %></td>
        <td><%= lg.imei %></td>
        <td><%= lg.response_email %></td>
        <td><%= lg.text_alert %></td>
        <td><%= lg.user_id %></td>
        <td><%=l lg.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lg_path(lg), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lg_path(lg),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lg_path,
            :class => 'btn btn-primary' %>

app/views/lgs/new.html.erb
<%- model_class = Lg -%>
<div class="page-header">
  <h1>LG Service</h1>
</div>
<%= render :partial => 'form' %>

app/views/lgs/show.html.erb
<%- model_class = Lg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:services) %>:</strong></dt>
  <dd><%= @lg.services %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imei) %>:</strong></dt>
  <dd><%= @lg.imei %></dd>
  <dt><strong><%= model_class.human_attribute_name(:response_email) %>:</strong></dt>
  <dd><%= @lg.response_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text_alert) %>:</strong></dt>
  <dd><%= @lg.text_alert %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @lg.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lgs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lg_path(@lg), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lg_path(@lg),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>