config/routes.rb
Unlocking::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users 
  resources :blackberries
  resources :alcatels
  resources :huwaeis
  resources :htcs
  resources :lgs
  resources :samsungs
  resources :iphones

  
  
  get "pages/contact"

end

app/models/htc.rb
class Htc < ActiveRecord::Base
  belongs_to :user
end

app/controllers/htcs_controller.rb
class HtcsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_htc, only: [:show, :edit, :update, :destroy]

  # GET /htcs
  # GET /htcs.json
  def index
    @htcs = Htc.all
  end

  # GET /htcs/1
  # GET /htcs/1.json
  def show
  end

  # GET /htcs/new
  def new
    @htc = Htc.new
  end

  # GET /htcs/1/edit
  def edit
  end

  # POST /htcs
  # POST /htcs.json
  def create
    @htc = Htc.new(htc_params)

    respond_to do |format|
      if @htc.save
        format.html { redirect_to @htc, notice: 'Htc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @htc }
      else
        format.html { render action: 'new' }
        format.json { render json: @htc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /htcs/1
  # PATCH/PUT /htcs/1.json
  def update
    respond_to do |format|
      if @htc.update(htc_params)
        format.html { redirect_to @htc, notice: 'Htc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @htc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /htcs/1
  # DELETE /htcs/1.json
  def destroy
    @htc.destroy
    respond_to do |format|
      format.html { redirect_to htcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_htc
      @htc = Htc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def htc_params
      params.require(:htc).permit(:services, :imei, :response_email, :text_alert, :user_id)
    end
end

app/helpers/htcs_helper.rb
module HtcsHelper
end

app/views/htcs/_form.html.erb
<%= form_for @htc, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :services, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :services,['HTC (2009-2012) $10 (Instant)','HTC (2009-2012) $6 (2-24hrs)','HTC(2013-2014) $34 (Instant)'],:prompt => "Select One", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imei, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imei, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :response_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :response_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text_alert, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text_alert, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                htcs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/htcs/edit.html.erb
<%- model_class = Htc -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/htcs/index.html.erb
<%- model_class = Htc -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:services) %></th>
      <th><%= model_class.human_attribute_name(:imei) %></th>
      <th><%= model_class.human_attribute_name(:response_email) %></th>
      <th><%= model_class.human_attribute_name(:text_alert) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @htcs.each do |htc| %>
      <tr>
        <td><%= link_to htc.id, htc_path(htc) %></td>
        <td><%= htc.services %></td>
        <td><%= htc.imei %></td>
        <td><%= htc.response_email %></td>
        <td><%= htc.text_alert %></td>
        <td><%= htc.user_id %></td>
        <td><%=l htc.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_htc_path(htc), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      htc_path(htc),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_htc_path,
            :class => 'btn btn-primary' %>

app/views/htcs/new.html.erb
<%- model_class = Htc -%>
<div class="page-header">
  <h1>HTC Service</h1>
</div>
<%= render :partial => 'form' %>

app/views/htcs/show.html.erb
<%- model_class = Htc -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:services) %>:</strong></dt>
  <dd><%= @htc.services %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imei) %>:</strong></dt>
  <dd><%= @htc.imei %></dd>
  <dt><strong><%= model_class.human_attribute_name(:response_email) %>:</strong></dt>
  <dd><%= @htc.response_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text_alert) %>:</strong></dt>
  <dd><%= @htc.text_alert %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @htc.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              htcs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_htc_path(@htc), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              htc_path(@htc),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>