config/routes.rb
Unlocking::Application.routes.draw do

  root :to => "pages#home"

  devise_for :users 
  resources :blackberries
  resources :alcatels
  resources :huwaeis
  resources :htcs
  resources :lgs
  resources :samsungs
  resources :iphones

  
  
  get "pages/contact"

end

app/models/alcatel.rb
class Alcatel < ActiveRecord::Base
  belongs_to :user
end

app/models/blackberry.rb
class Blackberry < ActiveRecord::Base
  belongs_to :user
end

app/models/htc.rb
class Htc < ActiveRecord::Base
  belongs_to :user
end

app/models/huwaei.rb
class Huwaei < ActiveRecord::Base
  belongs_to :user
end

app/models/iphone.rb
class Iphone < ActiveRecord::Base
  belongs_to :user
end

app/models/lg.rb
class Lg < ActiveRecord::Base
  belongs_to :user
end

app/models/samsung.rb
class Samsung < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :alcatels
         has_many :blackberries
         has_many :htcs
         has_many :lgs
         has_many :samsungs
         has_many :iphones
         has_many :huwaeis
end

app/controllers/htcs_controller.rb
class HtcsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_htc, only: [:show, :edit, :update, :destroy]

  # GET /htcs
  # GET /htcs.json
  def index
    @htcs = Htc.all
  end

  # GET /htcs/1
  # GET /htcs/1.json
  def show
  end

  # GET /htcs/new
  def new
    @htc = Htc.new
  end

  # GET /htcs/1/edit
  def edit
  end

  # POST /htcs
  # POST /htcs.json
  def create
    @htc = Htc.new(htc_params)

    respond_to do |format|
      if @htc.save
        format.html { redirect_to @htc, notice: 'Htc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @htc }
      else
        format.html { render action: 'new' }
        format.json { render json: @htc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /htcs/1
  # PATCH/PUT /htcs/1.json
  def update
    respond_to do |format|
      if @htc.update(htc_params)
        format.html { redirect_to @htc, notice: 'Htc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @htc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /htcs/1
  # DELETE /htcs/1.json
  def destroy
    @htc.destroy
    respond_to do |format|
      format.html { redirect_to htcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_htc
      @htc = Htc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def htc_params
      params.require(:htc).permit(:services, :imei, :response_email, :text_alert, :user_id)
    end
end

app/controllers/lgs_controller.rb
class LgsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_lg, only: [:show, :edit, :update, :destroy]

  # GET /lgs
  # GET /lgs.json
  def index
    @lgs = Lg.all
  end

  # GET /lgs/1
  # GET /lgs/1.json
  def show
  end

  # GET /lgs/new
  def new
    @lg = Lg.new
  end

  # GET /lgs/1/edit
  def edit
  end

  # POST /lgs
  # POST /lgs.json
  def create
    @lg = Lg.new(lg_params)

    respond_to do |format|
      if @lg.save
        format.html { redirect_to @lg, notice: 'Lg was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lg }
      else
        format.html { render action: 'new' }
        format.json { render json: @lg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgs/1
  # PATCH/PUT /lgs/1.json
  def update
    respond_to do |format|
      if @lg.update(lg_params)
        format.html { redirect_to @lg, notice: 'Lg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgs/1
  # DELETE /lgs/1.json
  def destroy
    @lg.destroy
    respond_to do |format|
      format.html { redirect_to lgs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lg
      @lg = Lg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lg_params
      params.require(:lg).permit(:services, :imei, :response_email, :text_alert, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

  def contact
  end
end

app/helpers/alcatels_helper.rb
module AlcatelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blackberries_helper.rb
module BlackberriesHelper
end

app/helpers/htcs_helper.rb
module HtcsHelper
end

app/helpers/huwaeis_helper.rb
module HuwaeisHelper
end

app/helpers/iphones_helper.rb
module IphonesHelper
end

app/helpers/lgs_helper.rb
module LgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/samsungs_helper.rb
module SamsungsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Unlocking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<div class='container'>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Unlocking</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li></li>
              <li></li>
              <li></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div>
            <ul class="nav nav-tabs nav-stacked">
              <li class="nav-header">SERVICES</li>
              <li><%= link_to "Iphone Unlocking", new_iphone_path %></li>
              <li><%= link_to "Samsung Unlocking", new_samsung_path%></li>
              <li><%= link_to "LG Unlocking", new_lg_path%></li>
              <li><%= link_to "HTC Unlocking", new_htc_path%></li>
              <li><%= link_to "Huwaei Unlocking", new_huwaei_path %></li>
              <li><%= link_to "Alcatel Unlocking", new_alcatel_path %></li>
               <li><%= link_to "Blackbery Unlocking", new_blackberry_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->
</div>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="hero-unit">
  <h1>Welcome to Unlocks</h1>
  <p>Unlocking your phones...Lightning Fast!!</p>
  <p>
    <a class="btn btn-primary btn-large">
      Learn more
    </a>
  </p>
</div>